# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Add To GitHub projects

on:
  workflow_dispatch:

  issues:
    types:
      - opened

  pull_request:
    types:
      - opened

jobs:
  add-to-project:
    name: Add To GitHub projects
    runs-on: ubuntu-latest

    # permissions:
    #   issues: write
    #   pull-requests: write
    #   repository-projects: write

    steps:
      - name: Add To GitHub projects
        uses: actions/add-to-project@v0.4.1
        with:
          project-url: https://github.com/users/AliMD/projects/3
          github-token: ${{secrets.ADD_TO_PROJECT}}
          # labeled: a, b
          # label-operator: AND
